# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleUnitTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleUnitTests

  target 'SimpleUnitTestsTests' do
    inherit! :search_paths
pod "AFNetworking", "~> 2.0"
pod 'Expecta'
  pod 'KVOController'
    # Pods for testing
  end

  target 'SimpleUnitTestsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
