# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift_rx' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'SnapKit',    '~> 5.0.0'
  pod 'Kingfisher', '~>4.0'
  # Pods for Swift_rx

end
